apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "milvus.fullname" . }}
  labels:
    {{- include "milvus.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "milvus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "milvus.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: milvus
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: milvus
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: "ETCD_ENDPOINTS"
              value: "etcd:2379"
            - name: "MINIO_ADDRESS"
              value: "minio:9000"
            - name: "MINIO_ACCESS_KEY"
              valueFrom:
                secretKeyRef:
                  name: milvus-minio-secret
                  key: accesskey
            - name: "MINIO_SECRET_KEY"
              valueFrom:
                secretKeyRef:
                  name: milvus-minio-secret
                  key: secretkey
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}