apiVersion: v1
kind: Service
metadata:
  name: {{ include "milvus.fullname" . }}
  labels:
    {{- include "milvus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: milvus
      protocol: TCP
      name: milvus
  selector:
    {{- include "milvus.selectorLabels" . | nindent 4 }}