global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'somabrain_dev'
    static_configs:
      - targets: ['host.docker.internal:30101']
    metrics_path: '/metrics'
